# Generated by Django 3.0.7 on 2020-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_de_naissance', models.DateField()),
                ('courriel', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=20)),
                ('NativeSpeeker', models.CharField(max_length=20)),
                ('PracticeSpeeker', models.CharField(max_length=20)),
                ('mot_de_passe', models.CharField(max_length=32)),
            ],
        ),
    ]
