# Generated by Django 3.0.7 on 2020-06-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userchat', '0002_auto_20200626_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='post_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Gendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gendar', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='NativeSpeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matNSpeakN', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PracticalSpeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matpSpeak', models.CharField(max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='personne',
            old_name='matricule',
            new_name='nomPrenom',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='personne',
            name='amis',
            field=models.ManyToManyField(blank=True, related_name='_personne_amis_+', to='userchat.Personne'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='NativeSpeeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userchat.NativeSpeeker'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='PracticeSpeeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userchat.PracticalSpeeker'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userchat.Countries'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='gendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userchat.Gendar'),
        ),
    ]
