# Generated by Django 3.0.7 on 2020-06-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userchat', '0003_auto_20200628_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='prenom',
            field=models.CharField(default='NONE', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personne',
            name='NativeSpeeker',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personne',
            name='PracticeSpeeker',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personne',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personne',
            name='gendar',
            field=models.CharField(default='None', max_length=3),
        ),
        migrations.AlterField(
            model_name='personne',
            name='nomPrenom',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='Gendar',
        ),
        migrations.DeleteModel(
            name='NativeSpeeker',
        ),
        migrations.DeleteModel(
            name='PracticalSpeeker',
        ),
    ]
