# Generated by Django 3.0.7 on 2020-06-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userchat', '0004_auto_20200628_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='post_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Gendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='NativeSpeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matNSpeakN', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PracticalSpeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matpSpeak', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='personne',
            name='nomPrenom',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='prenom',
        ),
        migrations.AddField(
            model_name='personne',
            name='Prenom',
            field=models.CharField(default='None', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personne',
            name='nom',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personne',
            name='NativeSpeeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userchat.NativeSpeeker'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='PracticeSpeeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userchat.PracticalSpeeker'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userchat.Countries'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='gendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userchat.Gendar'),
        ),
    ]
