# Generated by Django 3.0.7 on 2020-06-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userchat', '0005_auto_20200628_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nativespeeker',
            name='matNSpeakN',
            field=models.CharField(max_length=10),
        ),
    ]
