# Generated by Django 3.0.7 on 2020-07-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userchat', '0006_auto_20200630_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_de_publication',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='amis',
            field=models.ManyToManyField(blank=True, null=True, related_name='_personne_amis_+', to='userchat.Personne'),
        ),
    ]
